mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /etc/mihomo/ui
#external-ui-name: yacd
secret: "123456"

tun:
    enable: true
    stack: system
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
      - 192.168.98.1:53 # 搭配mosdns时需要关闭DNS劫持
    
proxy-providers:
  BGW:
   type: http
   path: ./provider/bgw.yaml
   url: "https://example.com"
   interval: 28800
   proxy: DIRECT
   health-check:
     enable: true
     url: http://www.gstatic.com/generate_204
     interval: 300
  VULTR:
   type: http
   path: ./provider/vultr.yaml
   url: "https://example.com"
   interval: 28800
   proxy: DIRECT
   health-check:
     enable: true
     url: http://www.gstatic.com/generate_204
     interval: 300
     
proxy-groups:
  - name: "NETFLIX"
    type: load-balance
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300
    use:
      - VULTR  
  - name: "URLTEST"
    type: load-balance
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300
    use:
      - BGW
  - name: "SELECT"
    type: select
    use:
      - BGW
  - name: "PROXY"
    type: select
    proxies:
      - DIRECT
      - URLTEST
      - SELECT

rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,NETFLIX,NETFLIX
  - MATCH,PROXY